apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-app-vs
  namespace: {{.Values.istio.namespaceName}}
spec:
  hosts:
    {{ if .Values.istio.host }}
    - {{ .Values.istio.host }}
    {{ else}}
    - "*"
    {{ end }}
  gateways:
    - {{ .Values.istio.gateway }}
  http:
    - match:
        - uri:
          prefix: {{ .Values.istio.prefix }}
      route:
        - destination:
            host: {{ include "task-app.fullname" . }}.opsfleat-task.svc.cluster.local
            port:
              number: 80


