istio:
  namespaceName: opsfleat-task
  gateway: default/default-gateway
  prefix: /
replicaCount: 3
image:
  repository: image
  pullPolicy: IfNotPresent
  tag: "tag"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {} 

service:
  type: ClusterIP
  svc_port: 80
  container_port: 8080

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
readinessProbe:
  httpGet:
    path: /health
    port: http

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
volumes: []

volumeMounts: []


nodeSelector: {}

tolerations: []

affinity: {}
